# Generated by Django 3.1.4 on 2020-12-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordToCorrect',
        ),
    ]
